"""Tests for context engineering strategies section in auto-generated CLAUDE.md (v1.1.3).

v1.1.3 (Part B) adds a "## Context Engineering Strategies" section to the
CLAUDE.md generated by _write_agent_claude_md(). The section documents the
four strategies (Write / Select / Compress / Isolate) with role-specific guidance.

Reference: DESIGN.md §10.39 (v1.1.3 — Context 4-Strategy Guide)
Sources: Zilliz "Context Engineering for AI Agents" (2025)
         LangChain "Context Engineering for Agents" (2025)
"""
from __future__ import annotations

from pathlib import Path
from unittest.mock import MagicMock

import pytest

from tmux_orchestrator.agents.claude_code import ClaudeCodeAgent
from tmux_orchestrator.bus import Bus
from tmux_orchestrator.config import AgentRole


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------


def make_bus() -> Bus:
    return Bus()


def make_tmux_mock():
    tmux = MagicMock()
    return tmux


def make_agent(agent_id: str = "worker-1", role: AgentRole = AgentRole.WORKER) -> ClaudeCodeAgent:
    return ClaudeCodeAgent(
        agent_id=agent_id,
        bus=make_bus(),
        tmux=make_tmux_mock(),
        role=role,
        web_base_url="http://localhost:8000",
    )


def write_and_read(agent: ClaudeCodeAgent, tmp_path: Path) -> str:
    """Write CLAUDE.md to tmp_path and return its content."""
    agent._write_agent_claude_md(tmp_path)
    return (tmp_path / "CLAUDE.md").read_text(encoding="utf-8")


# ---------------------------------------------------------------------------
# Tests
# ---------------------------------------------------------------------------


def test_claude_md_contains_context_strategies_section(tmp_path: Path) -> None:
    """Generated CLAUDE.md must contain a 'Context Engineering Strategies' section."""
    agent = make_agent()
    content = write_and_read(agent, tmp_path)
    assert "Context Engineering Strategies" in content, (
        "CLAUDE.md must contain 'Context Engineering Strategies' section"
    )


def test_claude_md_contains_write_strategy(tmp_path: Path) -> None:
    """Generated CLAUDE.md must document the Write strategy."""
    agent = make_agent()
    content = write_and_read(agent, tmp_path)
    assert "Write" in content, "CLAUDE.md must document the Write strategy"


def test_claude_md_contains_select_strategy(tmp_path: Path) -> None:
    """Generated CLAUDE.md must document the Select strategy."""
    agent = make_agent()
    content = write_and_read(agent, tmp_path)
    assert "Select" in content, "CLAUDE.md must document the Select strategy"


def test_claude_md_contains_compress_strategy(tmp_path: Path) -> None:
    """Generated CLAUDE.md must document the Compress strategy."""
    agent = make_agent()
    content = write_and_read(agent, tmp_path)
    assert "Compress" in content, "CLAUDE.md must document the Compress strategy"


def test_claude_md_contains_isolate_strategy(tmp_path: Path) -> None:
    """Generated CLAUDE.md must document the Isolate strategy."""
    agent = make_agent()
    content = write_and_read(agent, tmp_path)
    assert "Isolate" in content, "CLAUDE.md must document the Isolate strategy"


def test_claude_md_worker_recommendation_present(tmp_path: Path) -> None:
    """Worker agent CLAUDE.md must contain worker-specific strategy guidance."""
    agent = make_agent(role=AgentRole.WORKER)
    content = write_and_read(agent, tmp_path)
    assert "Worker" in content, "Worker CLAUDE.md must contain worker-specific guidance"


def test_claude_md_director_recommendation_present(tmp_path: Path) -> None:
    """Director agent CLAUDE.md must contain director-specific strategy guidance."""
    agent = make_agent(agent_id="director-1", role=AgentRole.DIRECTOR)
    content = write_and_read(agent, tmp_path)
    assert "Director" in content, "Director CLAUDE.md must contain director-specific guidance"


def test_claude_md_summarize_mentioned_in_compress(tmp_path: Path) -> None:
    """/summarize must be mentioned as the Compress tool in the strategies section."""
    agent = make_agent()
    content = write_and_read(agent, tmp_path)
    assert "/summarize" in content, "/summarize must be mentioned in Compress strategy"


def test_claude_md_spawn_subagent_mentioned_in_isolate(tmp_path: Path) -> None:
    """/spawn-subagent must be mentioned as the Isolate tool in the strategies section."""
    agent = make_agent()
    content = write_and_read(agent, tmp_path)
    assert "/spawn-subagent" in content, "/spawn-subagent must be mentioned in Isolate strategy"


def test_claude_md_context_rot_warning_present(tmp_path: Path) -> None:
    """The context rot warning must be present to help agents self-diagnose."""
    agent = make_agent()
    content = write_and_read(agent, tmp_path)
    assert "context rot" in content, "Context rot warning must be present in CLAUDE.md"


def test_claude_md_strategies_section_has_table(tmp_path: Path) -> None:
    """The strategies section must include a markdown table for quick reference."""
    agent = make_agent()
    content = write_and_read(agent, tmp_path)
    # Markdown table rows start with |
    strategies_idx = content.find("Context Engineering Strategies")
    assert strategies_idx != -1
    strategies_section = content[strategies_idx:]
    assert "|" in strategies_section, (
        "Strategies section must contain a markdown table"
    )


def test_claude_md_director_no_worker_recommendation(tmp_path: Path) -> None:
    """Director CLAUDE.md must not show Worker-specific sequence."""
    agent = make_agent(agent_id="director-1", role=AgentRole.DIRECTOR)
    content = write_and_read(agent, tmp_path)
    # Worker sequence hint says "Recommended sequence (Worker)"
    # Director hint says "Recommended sequence (Director)"
    # They should not be interchanged
    strategies_idx = content.find("Context Engineering Strategies")
    assert strategies_idx != -1
    strategies_section = content[strategies_idx:]
    assert "Recommended sequence (Director)" in strategies_section, (
        "Director CLAUDE.md must show director-specific sequence"
    )
    assert "Recommended sequence (Worker)" not in strategies_section, (
        "Director CLAUDE.md must not show worker-specific sequence"
    )
