"""Stateful property tests for AgentStatus lifecycle using Hypothesis.

Models the valid ``AgentStatus`` state machine and verifies invariants hold
across arbitrary transition sequences generated by Hypothesis.

State machine modelled:
  STOPPED  → IDLE      (agent started / registered)
  IDLE     → BUSY      (task dispatched)
  IDLE     → DRAINING  (drain requested)
  BUSY     → IDLE      (task completed normally)
  BUSY     → ERROR     (task failed / timeout)
  BUSY     → DRAINING  (drain requested while task in progress)
  ERROR    → IDLE      (auto-recovery / reset)
  ERROR    → STOPPED   (agent removed)
  DRAINING → IDLE      (drain complete, agent ready again)
  DRAINING → STOPPED   (agent removed during drain)
  IDLE     → STOPPED   (agent removed)

Invariants checked on every step:
  1. status is always one of the defined AgentStatus values.
  2. task_count is always >= 0.
  3. total_dispatched >= total_completed + total_errors.
  4. If status is BUSY, exactly one task is in-flight (task_count == 1).
  5. If status is IDLE or STOPPED or DRAINING, no task is in-flight (task_count == 0).

References:
  - Hypothesis docs "Stateful Testing" https://hypothesis.readthedocs.io/en/latest/stateful.html
  - Claessen & Hughes "QuickCheck" (ICFP 2000) https://dl.acm.org/doi/10.1145/357766.351266
  - MacIver "In praise of property-based testing" Increment Magazine (2019)
  - DESIGN.md §10.33 (v1.0.33 — AgentStatus Hypothesis stateful tests)
"""

from __future__ import annotations

from hypothesis import HealthCheck, assume, settings
from hypothesis.stateful import RuleBasedStateMachine, initialize, invariant, rule

from tmux_orchestrator.domain.agent import AgentStatus


# ---------------------------------------------------------------------------
# Model of the AgentStatus state machine
# ---------------------------------------------------------------------------


class AgentStatusMachine(RuleBasedStateMachine):
    """Models a single agent's status lifecycle.

    The machine tracks an agent's status and a count of in-flight tasks,
    then verifies invariants after every generated transition sequence.

    This is a *model* of valid transitions — not a test of any specific
    implementation.  Adding a new transition path here and running the tests
    will immediately reveal if the implementation does not cover that path.
    """

    def __init__(self) -> None:
        super().__init__()
        self.status: AgentStatus = AgentStatus.STOPPED
        self.task_count: int = 0        # 0 or 1 (at most one task per agent)
        self.total_dispatched: int = 0
        self.total_completed: int = 0
        self.total_errors: int = 0

    # -----------------------------------------------------------------------
    # Initialiser: move agent to IDLE (started state)
    # -----------------------------------------------------------------------

    @initialize()
    def start_agent(self) -> None:
        """Transition STOPPED → IDLE (agent registered and ready)."""
        self.status = AgentStatus.IDLE
        self.task_count = 0

    # -----------------------------------------------------------------------
    # Transitions (rules)
    # -----------------------------------------------------------------------

    @rule()
    def dispatch_task(self) -> None:
        """IDLE → BUSY: orchestrator dispatches a task to the agent."""
        assume(self.status == AgentStatus.IDLE)
        self.status = AgentStatus.BUSY
        self.task_count += 1
        self.total_dispatched += 1

    @rule()
    def complete_task(self) -> None:
        """BUSY → IDLE: agent completes the task successfully."""
        assume(self.status == AgentStatus.BUSY)
        self.status = AgentStatus.IDLE
        self.task_count -= 1
        self.total_completed += 1

    @rule()
    def fail_task(self) -> None:
        """BUSY → ERROR: task fails or times out."""
        assume(self.status == AgentStatus.BUSY)
        self.status = AgentStatus.ERROR
        self.task_count -= 1
        self.total_errors += 1

    @rule()
    def drain_while_idle(self) -> None:
        """IDLE → DRAINING: drain requested when agent is idle."""
        assume(self.status == AgentStatus.IDLE)
        self.status = AgentStatus.DRAINING

    @rule()
    def drain_while_busy(self) -> None:
        """BUSY → DRAINING: drain requested while agent is processing a task.

        The in-flight task count stays 1 until drain completes.
        This is a transitional state — the task finishes first.
        """
        assume(self.status == AgentStatus.BUSY)
        # In the real implementation, drain while busy means:
        # the agent finishes its current task then stops accepting new ones.
        # We model the moment the task finishes (count decrements).
        self.status = AgentStatus.DRAINING
        self.task_count -= 1
        self.total_completed += 1

    @rule()
    def recover_from_error(self) -> None:
        """ERROR → IDLE: auto-recovery or manual reset returns agent to idle."""
        assume(self.status == AgentStatus.ERROR)
        self.status = AgentStatus.IDLE

    @rule()
    def complete_drain(self) -> None:
        """DRAINING → IDLE: drain complete, agent ready to accept tasks again."""
        assume(self.status == AgentStatus.DRAINING)
        self.status = AgentStatus.IDLE

    @rule()
    def stop_from_idle(self) -> None:
        """IDLE → STOPPED: agent removed gracefully."""
        assume(self.status == AgentStatus.IDLE)
        self.status = AgentStatus.STOPPED

    @rule()
    def stop_from_error(self) -> None:
        """ERROR → STOPPED: failed agent removed from registry."""
        assume(self.status == AgentStatus.ERROR)
        self.status = AgentStatus.STOPPED

    @rule()
    def stop_from_draining(self) -> None:
        """DRAINING → STOPPED: agent removed during drain."""
        assume(self.status == AgentStatus.DRAINING)
        self.status = AgentStatus.STOPPED

    # -----------------------------------------------------------------------
    # Invariants — checked after every step
    # -----------------------------------------------------------------------

    @invariant()
    def status_is_valid_enum_member(self) -> None:
        """Status is always a defined AgentStatus value."""
        assert self.status in AgentStatus

    @invariant()
    def task_count_is_non_negative(self) -> None:
        """task_count never goes below zero."""
        assert self.task_count >= 0, f"task_count={self.task_count} < 0"

    @invariant()
    def dispatched_ge_completed_plus_errors(self) -> None:
        """Total dispatched >= total completed + total errors (no double-counting)."""
        assert self.total_dispatched >= self.total_completed + self.total_errors, (
            f"dispatched={self.total_dispatched} < "
            f"completed+errors={self.total_completed + self.total_errors}"
        )

    @invariant()
    def busy_iff_task_in_flight(self) -> None:
        """If status is BUSY exactly one task is in-flight; otherwise none."""
        if self.status == AgentStatus.BUSY:
            assert self.task_count == 1, (
                f"BUSY but task_count={self.task_count} (expected 1)"
            )
        elif self.status in (
            AgentStatus.IDLE,
            AgentStatus.STOPPED,
            AgentStatus.DRAINING,
            AgentStatus.ERROR,
        ):
            assert self.task_count == 0, (
                f"{self.status} but task_count={self.task_count} (expected 0)"
            )

    @invariant()
    def stopped_implies_no_tasks(self) -> None:
        """A STOPPED agent has no in-flight tasks."""
        if self.status == AgentStatus.STOPPED:
            assert self.task_count == 0


# Run the machine as a pytest test with Hypothesis settings.
TestAgentStatusMachine = AgentStatusMachine.TestCase
TestAgentStatusMachine.settings = settings(
    max_examples=200,
    stateful_step_count=20,
    suppress_health_check=[HealthCheck.too_slow, HealthCheck.filter_too_much],
)
